USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE my_task_wh
WAREHOUSE_SIZE = 'X-Small'
AUTO_SUSPEND = 60;

USE DATABASE source_db;
USE SCHEMA cdc_schema;
USE WAREHOUSE compute_wh;

CREATE OR REPLACE TASK cdc_schema.customer_cdc_task
WAREHOUSE = my_task_wh
SCHEDULE = '15 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SOURCE_DB.SOURCE_SCHEMA.CUSTOMER_STREAM')
AS
CALL cdc_schema.sp_update_cdc();
